### ISSUE TITLE
Does your plugin support rename MACRO(e.g.`#define Foo ...`) in C?

### ISSUE THREAD

**Issue by nyngwang** [filipdutescu/renamer.nvim#104]
As title. The plugin I'm using cannot rename the `Foo`.

**Comment by filipdutescu** [comment]
That is not something it handles, the LSP server you are using is the one that decides that. I haven't tested this scenario so I couldn't answer with which LSP can do it. You need to check with them.

**Comment by filipdutescu** [comment]
Not really something I can fix... maybe the `clangd` team can help you out if you open an issue there. Or maybe they can implement the feature. Closing since it is not related to `renamer` but to the LSP server.
