### ISSUE TITLE
[Bug] Changes is nil on any rename.

### ISSUE THREAD

**Issue by aloussase** [filipdutescu/renamer.nvim#106]
# Describe the bug

I get an error saying that `changes` is `nil` everytime I rename something. The renaming itself looks like it's working correctly though. 

## To reproduce

1. Rename a symbol

## Expected behavior

The symbol is renamed and no errors occur.

## Environment

- **Renamer:** v3.0.3
- **Neovim:** v0.6.0
- **OS:** Pop! OS 21.10

### Screenshots

![image](https://user-images.githubusercontent.com/84427521/147745952-632788e0-e2ae-4211-831f-e7edb62ba95e.png)

### Additional context

Just installed it and run its `setup` function providing only the title. Then I am calling the `rename` function through a mapping.

**Comment by zim0369** [comment]
Same issue:
https://imgur.com/a/mBqqwM4

**Comment by filipdutescu** [comment]
Interesting, no clue why this is happening but will investigate and come up with a fix. Can I get the name of the LSP server's you are using?

**Comment by aloussase** [comment]
I was using ccls: https://github.com/MaskRay/ccls

**Comment by filipdutescu** [comment]
Could you switch temporarily to the `develop` branch and tell me if it isn't fixed? I worked on another issue with a similar problem and reworked the logic that breaks for you and @zim0369. The related issue was GH-100.

**Comment by filipdutescu** [comment]
I have just checked and it still reproduces on latest `develop`. Figured out why, now working on a fix.
