### ISSUE TITLE
[Bug] Horizontal padding is interpreted as literal text

### ISSUE THREAD

**Issue by piotr-machura** [filipdutescu/renamer.nvim#119]
# Describe the bug

First of all, thank you for making this amazing plugin!

The bug in question: horizontal padding can be removed with backspace and is interpreted as a part of the new variable name.

## To reproduce

Set `padding = { left = 3 }` (or any number greater than 0) in `require('renamer').setup` and try renaming something with `require('renamer').rename()` in eg. a python script:

![screenshot_453807](https://user-images.githubusercontent.com/59394665/153881111-3ef32613-00f4-4620-a8a2-c3885933aeb1.png)

The padding can be removed by simply pressing backspace a bunch:

![screenshot_138697](https://user-images.githubusercontent.com/59394665/153881136-edd1514c-3e8d-4485-a17c-d71a2d95f846.png)

and if, instead of removing, I simply confirm with `<CR>` padding is interpreted as part of the new name (notice the 3 spaces in front of `content` causing an indentation error):

![screenshot_182590](https://user-images.githubusercontent.com/59394665/153881249-780a9109-26da-4a75-aa47-08b15bc4d4e7.png)

## Expected behavior
The padding should be non-interactive and should not be treated like user input.

## Environment

- **Renamer:** *4.0.1*
- **Neovim:** *0.6.1*
- **OS:** *Arch Linux*

**Comment by filipdutescu** [comment]
Hello, thank you very much for reporting this bug! It seems like an easy fix at a first glance and I will ensure a fix is provided in the `5.0.0` version.

**Comment by filipdutescu** [comment]
Looking a bit more into it. I might not be able to do everything desired in this bug fix, as the deletion of padding seems to come from [nvim-lua/plenary.nvim](https://github.com/nvim-lua/plenary.nvim), rather than `renamer.nvim`. Do you want to open an issue on their side and link this one as well? The empty spaces used in the new name might also be from there, but this is something I might be able to handle on my side here.

**Comment by filipdutescu** [comment]
I have created https://github.com/nvim-lua/plenary.nvim/issues/365 to see what the maintainer thinks about this issue and will work on removing the empty spaces from the new name once I get an answer, since it might affect the implementation.
