### ISSUE TITLE
[Bug] Error when using <cmd>lua require("renamer").rename()<cr>

### ISSUE THREAD

**Issue by JjersaR** [filipdutescu/renamer.nvim#121]
# Describe the bug

When I try to use this command I get an error, it won't let me change the name of a function.

## To reproduce

Use version 0.7.0 of neovim, try to use that command and then, at least for me, it gives error.

## Expected behavior

It is expected to perform the rename action after pressing enter.

## Environment

- **Renamer:** *[I don't know how to know the version, but yesterday I updated the plugins.]*
- **Neovim:** *[v0.7.0]*
- **OS:** *[Fedora Linux]*, **version:** *[5.17.6-300.fc36.x86_64]*

### Screenshots

![image](https://user-images.githubusercontent.com/86206596/167966450-aa283946-8ad7-4ca8-9c10-19202795ee4d.png)
![image](https://user-images.githubusercontent.com/86206596/167966500-ba08ed9c-88e7-41af-abfc-9655ab59d719.png)

**Comment by filipdutescu** [comment]
Hi, thanks for reporting the bug! I have started work on fixing this and GH-117 in GH-122, which should ensure a more stable future-proof plugin.

**Comment by JjersaR** [comment]
Thanks for replying, it's a great plugin, I find it very useful.

**Comment by filipdutescu** [comment]
Of course, after all it's made for others, so I value all feedback! :grin:
