### ISSUE TITLE
Global renaming of variables

### ISSUE THREAD

**Issue by santiago-br** [filipdutescu/renamer.nvim#126]
## Proposal

Hey!

Is there some function to globally rename a variable? if not, you could integrate something like [this](https://www.reddit.com/r/neovim/comments/tjzmnt/better_lsp_rename/)

**Comment by filipdutescu** [comment]
Hey, thanks for the feature request. I'm not sure what you mean by globally rename a variable? It already does globally rename symbols, using the LSP server of you're language. Can you please clarify?

**Comment by santiago-br** [comment]
Hey Filip, yeah, I think I wasn't saving all the buffers, so I'm closing this issue 😄

**Comment by filipdutescu** [comment]
Glad you figured it out haha! Thanks for closing the issue and explaining you solution as well, in case others have the same problem! :grin:
