### ISSUE TITLE
Popup appear but nothing happens [Bug] 

### ISSUE THREAD

**Issue by YuCao16** [filipdutescu/renamer.nvim#127]
# Describe the bug

As the title says, I use command `lua require"renamer".rename()` and the popup window can appear, then I type in the name I want to rename and press enter, but nothing happens, none of the names have changed.

## To reproduce

Since no one report this issue, so I think it's because my own config problem. How can I debug it?

## Expected behavior

*A clear and concise description of what you expected to happen.*

## Environment

- **Renamer:** *[v5.0.0]*
- **Neovim:** *[v.0.7.2]*
- **OS:** *[Macos]*, **version:** *[12.4]*

### Screenshots

<img width="1920" alt="截屏2022-08-02 11 27 01" src="https://user-images.githubusercontent.com/62466929/182353366-8e1d8ef7-2906-4504-b5e1-649d14e24940.png">

### Additional context

*Add any other context about the problem here.*

**Comment by filipdutescu** [comment]
Hey, thanks for submitting this bug report! I will need a couple more details however, such as:

1. Have you called `renamer.setup()` before calling `renamer.rename()`
2. What LSP are you using and is it up and running before calling rename?
3. Is there no error message after rename is called?

**Comment by YuCao16** [comment]
Hi @filipdutescu , 
Sorry I don't know this plugin require LSP, I thought the plugin search for keywords in the file and then replace them. So it makes sense `renamer` do nothing since I'm using `coc.nvim` as LSP client.

**Comment by filipdutescu** [comment]
No need to apologise, I am glad you figured it out! Does this mean you fixed the issue?

**Comment by YuCao16** [comment]
Yeah, I think so, let me close this issue.

**Comment by filipdutescu** [comment]
Awesome! Feel free to reach out with any other bug/feature request!
