### ISSUE TITLE
[Bug] a ( in front of every varable/function

### ISSUE THREAD

**Issue by desdic** [filipdutescu/renamer.nvim#66]
# Describe the bug

When I activate rename the popup with the variable/function name is always prefixed with " )" (see screenshot)

config:
```
                use {
                        'filipdutescu/renamer.nvim',
                        branch = 'master',
                        requires = { {'nvim-lua/plenary.nvim'} },
                        config = function()
                                require("renamer").setup()
                        end
                }
```

## To reproduce

leader - rn

## Expected behavior

Variable/function without being prefixed

## Environment

- **Renamer:** latest master
- **Neovim:** 0.5.1-2
- **OS:** Arch

### Screenshots

![2021-11-09_073314_674286659](https://user-images.githubusercontent.com/13243026/140874362-b34b09f1-29e3-4362-b5ff-a23aa2b01ea6.png)

**Comment by filipdutescu** [comment]
Thanks for reporting this issue and trying out my plugin!

I cannot reproduce this behaviour with my config. Could you link me your Neovim config? I think that's where the problem comes from, since there is also a line number (which is not intended, as you can see from the media I show of the plugin)

**Comment by desdic** [comment]
> Thanks for reporting this issue and trying out my plugin!
> 
> I cannot reproduce this behaviour with my config. Could you link me your Neovim config? I think that's where the problem comes from, since there is also a line number (which is not intended, as you can see from the media I show of the plugin)

Sure .. my entire config is here https://github.com/desdic/dotfiles/tree/master/.config/nvim

**Comment by filipdutescu** [comment]
What language server are you using? Does this issue occur on other servers as well (ie rust/python/lua)?

**Comment by desdic** [comment]
I'm using go, python, ruby and lua. All have the same issue with the linenumber<space>)

**Comment by desdic** [comment]
Some of it seems to be related to 
cursorline = true, signcolumn = true, hybridnumber = true
but when I disable that I still get a ) but this time no number

**Comment by filipdutescu** [comment]
I suspected something like that with regards to the number. The `)` is really weird though, especially since it appears on multiple servers...

If you do a `:lua print(vim.fn.expand '<cword>')` while the cursor is on a word that shows `)` in the prompt, what do you get?

**Comment by desdic** [comment]
> I suspected something like that with regards to the number. The `)` is really weird though, especially since it appears on multiple servers...
> 
> If you do a `:lua print(vim.fn.expand '<cword>')` while the cursor is on a word that shows `)` in the prompt, what do you get?

Then I get the word I'm standing on so that seems correct :)

**Comment by desdic** [comment]
oki so if I disable the focus plugin I get the word but with ) and not the numbers but I still have relative numbers. So there might be something related to that plugin .. still looking for the )

**Comment by filipdutescu** [comment]
As far as I can tell, no extra `)` appears in my code... it might be some other plugin/autocmd messing with this plugin

**Comment by desdic** [comment]
Doh the extra ) is my bad 

set_keymap('n', '<Leader>rn',   '<cmd>lua require("renamer").rename()<CR>)', {noremap=true, silent=true})

I have en extra ) after <CR> .. sorry about that

**Comment by filipdutescu** [comment]
No worries, thanks for opening the issue and I am glad we managed to figure it out! Hope you have a nice time with `renamer.nvim` and will keep using it 😁

**Comment by filipdutescu** [comment]
I assume it is safe to close this issue, in this case?

**Comment by desdic** [comment]
> No worries, thanks for opening the issue and I am glad we managed to figure it out! Hope you have a nice time with `renamer.nvim` and will keep using it grin

I think its really nice so yes ! :)

**Comment by desdic** [comment]
Just for the record I managed to remove the number too .. in the focus plugin it adds numbers on all buftype which is pretty weird so I might file a bug on that :) but for reference it can be removed by

```
excluded_buftypes = {"popup"}
```
