### ISSUE TITLE
[Feature] Option to prompt renaming through nvim's prompt instead of UI

### ISSUE THREAD

**Issue by sdushantha** [filipdutescu/renamer.nvim#68]
# Describe the issue

Great project, I've been looking this type of plugin for a long time!

I personally would like it if there was a option to prompt the rename through the command input (not sure what its called) instead of a popup. It's just a personal thing, as I'm not a huge fan of having the popup.

## Proposal
It would be nice to have something like in the screenshot below
![image](https://user-images.githubusercontent.com/27065646/140954277-ab5ad476-4b67-46e1-8be7-5613d3980c40.png)

**Comment by filipdutescu** [comment]
Thanks for submitting feedback and for the proposal! I assume you already used `vim.lsp.buf.rename()` (since it kind does what you want), but would like to also have reference highlighting/the word to be renamed displayed.

Is this right? I am trying to get a better idea as to how this feature should be designed.

**Comment by sdushantha** [comment]
> I assume you already used vim.lsp.buf.rename() (since it kind does what you want), but would like to also have reference highlighting/the word to be renamed displayed.

No I did not try `vim.lsp.buf.rename()` because I don't think I saw in the README. But after trying it out, I have confirm that what you have mentioned is the same feature I am requesting :)

**Comment by filipdutescu** [comment]
Just added your proposed feature to the `develop` branch (4ef89d5). Feel free to try it out or wait until I publish `v2.0.0`, around Sunday (or when I finish the remaining 2 issues). Thanks for your patience!

**Comment by sdushantha** [comment]
Thank you! I really appreciate you taking the time to implement this feature!!

**Comment by filipdutescu** [comment]
With pleasure! Thanks for suggesting it!
