### ISSUE TITLE
[Bug] bad argument #2 to 'format' 

### ISSUE THREAD

**Issue by konapun** [filipdutescu/renamer.nvim#70]
# Describe the bug

When invoking `rename` I get
```
E5108: Error executing lua ...imvu47Wx/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:458: bad argument #2 to 'format' (number expected, got nil)
```

## To reproduce

1. Start neovim
2. Open a file (tested with zsh and javascript)
3. Invoke a keybinding to execute rename or type `:lua require('renamer').rename()` and hit Enter
4. Observe `bad argument #2 to 'format' (number expected, got nil)` error

## Expected behavior

The rename dialog shows

## Environment

- **Renamer:** *[v1.0.0]*
- **Neovim:** *v0.5.1*
- **OS:** *[Xubuntu Linux]*, **version:** *[21.04]*

### Additional context
**Lsp Client:** `efm`

**Comment by filipdutescu** [comment]
Thanks for trying out the plugin and for submitting this report (very well written as well)!

Does this reproduce with `vim.lsp.buf.rename()`? Or just with `renamer.nvim`?

**Comment by konapun** [comment]
Thanks for your work on this plugin! I was using Spectre but found it a bit too heavy for what I was looking for and this fits the bill perfectly.

It turns out this is a Neovim issue! I just tried `vim.lsp.buf.rename()` and after entering the "New Name" I get the error I reported earlier. I'll create an issue in the Neovim repo if one doesn't already exist :)

**Comment by konapun** [comment]
It ended up being a problem with the efm language server. After reinstalling efm renamer works great!

**Comment by filipdutescu** [comment]
Thanks for the kind praise! I am delighted to hear everything works for you now and that, thankfully, the issue was not with `renamer`!

Hearing that you switched to my plugin from another is really encouraging and nice to see! I hope you have a blast with it!
