### ISSUE TITLE
[Bug] Cursor defaults to beginning of line instead of end

### ISSUE THREAD

**Issue by mrjones2014** [filipdutescu/renamer.nvim#73]
# Describe the bug

Maybe this is intended behavior, if it is, there should be an option to switch it. When I trigger the plugin, the default cursor position is at the beginning of the line, I'd expect it to be at the end.

## To reproduce

1. Call `require('renamer').rename()` on something

## Expected behavior

The cursor position defaults to the end of the prompt in the popup.

## Environment

- **Renamer:** *v1.0.0*
- **Neovim:** *v0.5.1*
- **OS:** *MacOS 12.0.1, Apple M1 chip*

#### Actual

![CleanShot-2021-11-11-at-06 59 01](https://user-images.githubusercontent.com/8648891/141294394-55dfa7e1-a1d9-4c94-9463-a682f896c728.png)

#### Expected

![CleanShot-2021-11-11-at-06 59 17](https://user-images.githubusercontent.com/8648891/141294430-3edd8905-60a4-4ee6-b79b-785cce65d8f5.png)

**Comment by mrjones2014** [comment]
@filipdutescu close, but now I'm getting it one character from the end 😕 
![CleanShot-2021-11-12-at-10 36 16](https://user-images.githubusercontent.com/8648891/141492965-c81f9f7d-3593-4cd0-b29e-241e9bd1924d.png)

**Comment by filipdutescu** [comment]
That' the most it will let me go 🤔. Not sure why. Let's reopen for now.
