### ISSUE TITLE
empty rename not working

### ISSUE THREAD

**Issue by ChristianChiarulli** [filipdutescu/renamer.nvim#82]
![image](https://user-images.githubusercontent.com/29136904/141659253-414f6dd8-f93a-44fe-a459-bdd42d18d61d.png)

**Comment by filipdutescu** [comment]
Please format your bug report according to the template. If you do not provide me with the needed information I cannot help you.

**Comment by filipdutescu** [comment]
@ChristianChiarulli I cannot reproduce, please make sure you are on `v2.0.0`, you might not have updated `renamer`
