### ISSUE TITLE
[Feature] Add a handler for textDocument/rename

### ISSUE THREAD

**Issue by axieax** [filipdutescu/renamer.nvim#84]
# Describe the issue

I would like to be able to attach a handler to textDocument/rename which I can use to display renamed changes using nvim-notify. 

## Proposal

It would be nice to be able to pass a custom handler function into the rename function. 

### Alternatives

I am currently doing my own renamer (not too sure how to get the popup UI - which is why I want to try out this plugin.

### Additional context

This is the handler function I am currently using:
- https://github.com/axieax/dotconfig/blob/main/nvim/lua/lsp/rename.lua#L39-L89

This is how I am passing it into textDocument/rename:
- https://github.com/axieax/dotconfig/blob/main/nvim/lua/lsp/rename.lua#L145

**Comment by filipdutescu** [comment]
Thanks for the feature request! You propose an interesting idea, but I am stuck with the solution I want to come up with. Either add `notify` support in `renamer`, add custom handler support or both.

Since you came up with the proposal and as a potential/new user, which would you prefer.

**Comment by axieax** [comment]
Hi thanks for the quick response. I would say adding custom handler support may be better since not everyone will have notify available, and it allows for more customisations. However, it doesn't hurt to have both somewhere down the track as well :))

**Comment by filipdutescu** [comment]
I would add it as an optional dependency, of course, after all, `renamer` should be lightweight :smile:.

Regarding the handler, I think I should call it using the raw response, as received from the LSP server and anyone using a custom handler should parse it as they see fit.

Does this sound reasonable?

**Comment by axieax** [comment]
Yep that sounds about right. Is that similar to what I am doing?

**Comment by filipdutescu** [comment]
Honestly? Not sure, since I'm on mobile atm and it is hard to tell

**Comment by filipdutescu** [comment]
I think the handler should be passed in the `setup` function, rather than the `rename` one. I cannot see any reason to add it on every call to rename.

**Comment by filipdutescu** [comment]
Just an FYI, I wont add notify support just yet, since the handlers allow you to do exactly that, minimally, without adding additional dependencies to `renamer`. If more people request it I will add it then.

**Comment by axieax** [comment]
Hello thanks for the quick implementation. Just wanted to bring your attention to the LSP response, where some language servers use resp.changes (what's currently being used), whereas others such as jdtls use resp.documentChanges. This is why I parse them differently for my handler. It would be nice to see something like this included to the default set_qf_list as well :))
Please see my handler which includes comments about documentChanges as well [here](https://github.com/axieax/dotconfig/blob/40b9da64b15b4e8245e9a9473f3a000c30d68e2e/nvim/lua/lsp/rename.lua#L34-L71)

**Comment by filipdutescu** [comment]
Wait really? Why would they have different names :sad:. Could you give me some examples of servers using `documentChanges`?

**Comment by axieax** [comment]
Yeah it's quite annoying. The only one I'm familiar with is jdt.ls (java), but from doing a quick google search, it seems like [palantir/python-language-server](https://github.com/natebosch/vim-lsc/issues/105#issuecomment-425671281) is doing it as well.

**Comment by filipdutescu** [comment]
Added support for `documentChanges` in LSP responses in 9341d33, hopefully this works as intended. Maybe you can validate the change if you're so kind?

**Comment by axieax** [comment]
Hi thanks again for the feature! It doesn't seem to work for jdtls due to a small bug, which I've fixed in PR #90 :))
