### ISSUE TITLE
[Bug] Rename prompt will be displayed even if no LSP is attached

### ISSUE THREAD

**Issue by EtiamNullam** [filipdutescu/renamer.nvim#96]
# Describe the bug

Attempting to rename text with no LSP attached will fail silently after displaying prompt for new name.

## To reproduce

1. Open file with no LSP attached.
2. Run `lua require('renamer').rename()` on any word.
4. Notice that nothing happens just like operation would be successful.

## Expected behavior

A discreet message should be displayed and no input box should be opened if there is nothing to rename.

## Environment

- **Renamer:** v3.0.2
- **Neovim:**  v0.5.1
- **OS:** Windows, **version:** 10

### Screenshots

![image](https://user-images.githubusercontent.com/10875340/143533258-8fe4e0c3-027a-44b9-918b-f1816e5e071c.png)

### Additional context

When LSP is attached the prompt will be shown also for invalid elements, but at least there is a warning displayed afterward.

**Comment by filipdutescu** [comment]
Thanks for reporting the bug! However, I am not sure how/if I can check if an LSP client is active for the current buffer. Will need to look into it.
